// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjY4NynWlmoYSKTy4GiO5cuALmwws5IUM',
    appId: '1:1095543884002:web:6a67b4d0250a2d9fc2b6bb',
    messagingSenderId: '1095543884002',
    projectId: 'manager-b70d7',
    authDomain: 'manager-b70d7.firebaseapp.com',
    storageBucket: 'manager-b70d7.appspot.com',
    measurementId: 'G-Z5S3J531XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDooiwCGPa5IZIoww6OnQAWybF34-r74XI',
    appId: '1:1095543884002:android:0703c2bbff4fb6fcc2b6bb',
    messagingSenderId: '1095543884002',
    projectId: 'manager-b70d7',
    storageBucket: 'manager-b70d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1s__N5REfy4Qa90s5Il6a1FjT2_7rlPQ',
    appId: '1:1095543884002:ios:974341d9d2aa182ac2b6bb',
    messagingSenderId: '1095543884002',
    projectId: 'manager-b70d7',
    storageBucket: 'manager-b70d7.appspot.com',
    iosBundleId: 'com.example.managerApp',
  );
}
